### ISSUE TITLE
Create A Footer Component

### ISSUE THREAD

**Issue by rdev0rigin** [CodeForPortland/recordexpungPDX#29]
Build a footer component that provides a copyright and terms link.

**Comment by rdev0rigin** [comment]
Going to merge this with the open [PR-30](https://github.com/CodeForPortland/recordexpungPDX/pull/30)

**Comment by hmarcks** [comment]
FYI I hid some footer markup in src/_frnt/webapp/index.html 

`    <footer class="pv6 black-50">
      <div class="mw8 ph2 center">
        <p class="f6"><a class="link underline hover-blue" href="#">Terms of use</a></p>
      </div>
    </footer>`
