### ISSUE TITLE
Build a project plan with milestones

### ISSUE THREAD

**Issue by quarterback** [CodeForPortland/recordexpungPDX#37]
Partner requests a project roadmap with timelines for deliverables. 

Describe the task here, including any supplemental information. 
Tag yourself, or whoever is responsible for it. 

### This task is done when...
 - [ ] a project plan is developed and team syncs on deliverables
 - [ ] plan is shared with partner agency

**Comment by maxkwallace** [comment]
Closing this issue since it hasn't been updated since Dec. To anyone: feel free to reopen it if you want to work on it!
