### ISSUE TITLE
Build project wiki on github

### ISSUE THREAD

**Issue by quarterback** [CodeForPortland/recordexpungPDX#38]
The project wiki on github provides external users with documentation about what our task is, what we're doing and ensures continuity when the project is handed off. 

Describe the task here, including any supplemental information. 
Tag yourself, or whoever is responsible for it. 

### This task is done when...
 - [ ] build out the project wiki

**Comment by maxkwallace** [comment]
Closing this issue since it hasn't been updated since Dec. To anyone: feel free to reopen it if you want to work on it!
