### ISSUE TITLE
Usability testing milestone

### ISSUE THREAD

**Issue by quarterback** [CodeForPortland/recordexpungPDX#39]
Once we have a prototype, we'll need an entire sprint focused around usability testing. Without testing users on the experience, we'll not be sure how to iterate on the existing design and validate our assumptions.

This is a milestone (epic) issue that will include all of the tasks for usability testing.

**Comment by maxkwallace** [comment]
Closing this issue since it hasn't been updated since Dec. To anyone: feel free to reopen it if you want to work on it!
