### ISSUE TITLE
type eligibility list interface

### ISSUE THREAD

**Issue by cameron2018** [CodeForPortland/recordexpungPDX#40]
I am currently hard coding a list of crimes that are ineligible for expungement (List A, List B, Etc.), however I get the feeling that maybe this list should be stored in the database and have some sort of interface so the public defenders office can view it and/or modify it as necessary. 

I imagine that these lists don't change very often, but i'd probably want this feature if i was them.

**Comment by NickSchimek** [comment]
Let's take a look at this when we pair next week.

**Comment by hmarcks** [comment]
I think a UI to make changes would be really convenient, but like you mentioned I don't think these rules will change much. I asked Michael about this a while ago and I think he said the same thing, he said getting in touch with a dev to make a change would be fine. But if it's relatively quick to implement, maybe it's worth it.

Also, it might be useful to have a UI that lists all the rules to quickly get an idea of how we're evaluating the records, even if it's not editable.

**Comment by a-ilango** [comment]
> Also, it might be useful to have a UI that lists all the rules to quickly get an idea of how we're evaluating the records, even if it's not editable.

The analyzer would output list of rules (as strings) that were checked and their result. So we could do it display it for every analysis if needed.

**Comment by NickSchimek** [comment]
I don't think we did talk about this. Our main goal is to deliver a minimal viable product that the client can use and give us feedback on. I too think this is a great idea, but it's not what the client is asking for at this point in time. The first step is to build the logic for analyzing a record, after that we can make iterative improvements based on the clients feedback. Will close this for now.
