### ISSUE TITLE
Update README for installing Python 3.7

### ISSUE THREAD

**Issue by erikjasso** [CodeForPortland/recordexpungPDX#50]
Need instructions for Mac and Linux

**Comment by cameron2018** [comment]
it appears that running "brew install python3" installs python 3.7.2 it on my mac, but it was already installed. it would be cool to verify that this works.

**Comment by cameron2018** [comment]
i find terrible non working install instructions on github all the time. it would be cool if we can test this. perhaps one of the new people?

**Comment by cameron2018** [comment]
I just tested "sudo apt-get install python3.7 -y" on my ubuntu 18.04 server and it works just fine

**Comment by maxkwallace** [comment]
I used the instructions from this answer https://askubuntu.com/a/1086830/219582 --

    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get install python3.7

which seemed to work fine.

**Comment by maxkwallace** [comment]
Closing this since it doesn't seem urgent and we haven't had any activity in a while. Feel free to reopen if you want to work it!
