### ISSUE TITLE
Fix errors in auth table

### ISSUE THREAD

**Issue by erikjasso** [CodeForPortland/recordexpungPDX#62]
The `auth` table has an extra comma and is missing a semicolon.

**Comment by maxkwallace** [comment]
@erikjasso it looks like this was addressed in #63 . Can we close this issue?

**Comment by erikjasso** [comment]
Resolved by #63. Closing.

**Comment by a-ilango** [comment]
A small trick with Github: if you mention the issue number in the PR in the following way, the issue will automatically get closed when the PR is merged:
Fixes #<issue number>
