### ISSUE TITLE
implement views as react components

### ISSUE THREAD

**Issue by josephhess** [CodeForPortland/recordexpungPDX#65]

**Comment by maxkwallace** [comment]
@josephhess Hey! I'm not trying to nag, just hoping to understand where the project is and what tasks are available for people to work on. How's this issue going, and do you have any in-progress code you can push up in a branch? If you're working on this I want to make sure that any changes I make in the frontend code aren't going to conflict with or duplicate what you're already working on.

**Comment by hmarcks** [comment]
I'm going to cancel this since we have a different frontend approach in progress.
