### ISSUE TITLE
Update name of analysis table to "analyses" to match pluralization in other tables 

### ISSUE THREAD

**Issue by maxkwallace** [CodeForPortland/recordexpungPDX#74]
Except for `auth`, the other tables in `config/postgres/initdb/scripts/create-tables.sql` are pluralized (`users`, `clients`, `rules`, etc.), so the `analysis` table probably should be `analyses` so it matches the other tables.

### This task is done when:
 - The "analysis" table is renamed to "analyses"

**Comment by maxkwallace** [comment]
@erikjasso `git blame` says you last edited that part of the `create-tables.sql` -- if you disagree with this change please go ahead and close the issue! (Just looking for small beginner-friendly tasks to get people familiar with the PR workflow.)

**Comment by ash-tamraz** [comment]
[Closed with PR #80](https://github.com/CodeForPortland/recordexpungPDX/pull/80).
