### ISSUE TITLE
Remove username from users table

### ISSUE THREAD

**Issue by a-ilango** [CodeForPortland/recordexpungPDX#77]
Remove username from users table and just use email for user identification. This is to keep things simple.

**Comment by ash-tamraz** [comment]
If someone wanted to work on this issue, they would need to remove [this line](https://github.com/CodeForPortland/recordexpungPDX/blob/master/config/postgres/initdb/scripts/create-tables.sql#L8)

```
    username CITEXT UNIQUE NOT NULL,
```
from the `users` table in `config/postgres/initdb/scripts/create-tables.sql`, correct?

**Comment by erikjasso** [comment]
@ash-tamraz Yes, that is correct.

**Comment by wittejm** [comment]
This change also requires removing all occurrences of the username field and replacing any occurrences with user email as the login handle. There are instances in the files

src/backend/expungeservice/endpoints/users.py
src/backend/expungeservice/endpoints/auth.py
src/backend/expungeservice/crawler/crawler.py
src/backend/expungeservice/crawler/request.py

along with their test cases and the design doc.

As far as I can tell there are currently no endpoint calls in the frontend that would be affected by this change, is that right?

**Comment by NickSchimek** [comment]
Most applications refer to the variable `username` even when the value being used is an email address. In our case an email address is a username. Username/password combination is needed to login. I suppose the files could be updated to state it's a `user_email`, but that doesn't necessarily convey that the variable is actually a username for login. I suppose the context it's being used in would imply that. I guess I'm saying I don't think it's necessary to make those change. What do you think?

**Comment by wittejm** [comment]
That makes sense. Though it seems not ideal to have the two fully redundant fields in endpoint data objects. If they're the same value there should only be one field.

I also realized that the occurrences of username crawler.py and request.py actually refer to the Oregon site's login, so would not be affected by this.

**Comment by NickSchimek** [comment]
Sounds good!
