### ISSUE TITLE
What is the difference between Inbox and Backlog in the Project?

### ISSUE THREAD

**Issue by maxkwallace** [CodeForPortland/recordexpungPDX#84]
Looking at the Project page https://github.com/CodeForPortland/recordexpungPDX/projects/2 I'm not sure what the difference is between the Inbox and Backlog columns. The difference should be clarified and added to the wiki here:

https://github.com/CodeForPortland/recordexpungPDX/wiki/Project-&-Issue-Management

### This task is done when...
 - The wiki page at https://github.com/CodeForPortland/recordexpungPDX/wiki/Project-&-Issue-Management has been updated to clarify how to use our Project.

**Comment by hmarcks** [comment]
Here's a proposal, but would love to hear other ideas:
• Change the "Inbox" column name to "Backlog". This will be for issues that aren't ready to be worked on yet or aren't prioritized.
• Change the "Backlog" column name to "Ready to Start". This is for issues that are ready to be worked on.
• Prioritize the most urgent issues at the top of each column.

**Comment by maxkwallace** [comment]
@hmarcks I'm in favor of that proposal.

**Comment by maxkwallace** [comment]
Just discussed the following with Hunter, who already updated the column names.

I propose to go and make the following additional changes to finish this issue:
- Go through and organize and prioritize the columns & issues in the columns to the extent possible
- Since-- once a card is in a column, e.g. "in progress", that status will appear on the right side of the issue page-- so some of the labels we have: "backlog", "in progress" are now redundant-- I plan to remove those so the only source of truth for the issue status "state machine" will be the Projects board
